[versions]
annotation = "1.9.1"
kotlin = "2.3.10"
lint = "32.0.1"
agp = "9.0.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
agp-lib = { id = "com.android.library", version.ref = "agp" }

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
